# Generated by Django 2.0.9 on 2018-11-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kwdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=4)),
                ('number', models.CharField(max_length=4)),
                ('correct', models.CharField(max_length=1)),
                ('kw_type', models.CharField(choices=[('NG', 'Nieruchomość gruntowa'), ('LM', 'Lokal mieszkalny')], max_length=2)),
            ],
        ),
    ]
