# Generated by Django 2.1.2 on 2018-11-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CracowDB', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kwdata',
            name='correct',
        ),
        migrations.RemoveField(
            model_name='kwdata',
            name='number',
        ),
        migrations.RemoveField(
            model_name='kwdata',
            name='prefix',
        ),
        migrations.AddField(
            model_name='kwdata',
            name='kw_number',
            field=models.CharField(default='', max_length=11),
        ),
    ]
