# Generated by Django 2.1.2 on 2018-11-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CracowDB', '0005_auto_20181119_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kwdata',
            name='kw_type',
            field=models.CharField(choices=[('NG', 'Nieruchomość gruntowa'), ('LM', 'Lokal stanowiący odrębną nieruchomość')], max_length=2),
        ),
    ]
