# Generated by Django 2.1.2 on 2018-11-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricespy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='one_product',
            name='image_name',
            field=models.CharField(default='photo', max_length=100),
            preserve_default=False,
        ),
    ]
